apiVersion: v1
kind: Secret
metadata:
  name: ndb-secret-name
type: Opaque
stringData:
  username: lizi
  password: password
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    CA CERTIFICATE (ca_certificate is optional)
    -----END CERTIFICATE-----
---
apiVersion: v1
kind: Secret
metadata:
  name: db-instance-secret-name
type: Opaque
stringData:
  password: password
  ssh_public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN4/sfvGjpnH/SqteI7Vzsh28++csx7RLRMeyaZ14zQa
